// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/unyooon/prompt-sharing/controller"
	"github.com/unyooon/prompt-sharing/domain"
	"github.com/unyooon/prompt-sharing/domain/setting"
	"github.com/unyooon/prompt-sharing/infrastructure/db"
	"github.com/unyooon/prompt-sharing/infrastructure/repository"
)

import (
	_ "github.com/unyooon/prompt-sharing/docs"
)

// Injectors from wire.go:

func InitializeHandler(s setting.Setting) *Routing {
	dbDb := db.NewDb(s)
	promptRepository := repository.NewPromptRepository(dbDb)
	llmMasterRepository := repository.NewLlmMasterRepository(dbDb)
	parameterMasterRepository := repository.NewParameterMasterRepository(dbDb)
	createPromptInteractor := domain.NewCreatePromptInteractor(promptRepository, llmMasterRepository, parameterMasterRepository)
	readPromptsInteractor := domain.NewReadPromptsInteractor(promptRepository)
	promptController := controller.NewPromptController(createPromptInteractor, readPromptsInteractor)
	userRepository := repository.NewUserRepository(dbDb)
	createUserInteractor := domain.NewCreateUserInteractor(userRepository)
	userController := controller.NewUserController(createUserInteractor)
	routing := NewRouting(promptController, userController, s)
	return routing
}
