// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "yuta"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/llm-masters": {
            "get": {
                "description": "Read LLM Masters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "llm_master"
                ],
                "summary": "Read LLM Masters",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dto.ReadLlmMasterResponse"
                            }
                        }
                    }
                }
            }
        },
        "/prompts": {
            "get": {
                "description": "read prompts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prompt"
                ],
                "summary": "Read Prompts",
                "parameters": [
                    {
                        "type": "boolean",
                        "name": "isPublic",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "llmId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ReadPromptsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "create prompt",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prompt"
                ],
                "summary": "Create Prompt",
                "parameters": [
                    {
                        "description": "prompt",
                        "name": "prompt",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePromptRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "ユーザーを登録します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "ユーザー登録",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BasePageResponse": {
            "type": "object",
            "properties": {
                "number": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        },
        "dto.CreatePromptRequest": {
            "type": "object",
            "required": [
                "description",
                "llmId",
                "parameters",
                "text"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "llmId": {
                    "type": "integer"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Parameter"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dto.CreatedUserResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                }
            }
        },
        "dto.Parameter": {
            "type": "object",
            "properties": {
                "parameterId": {
                    "type": "integer"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dto.ParameterResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "dto.ReadLlmMasterResponse": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "llmId": {
                    "type": "integer"
                }
            }
        },
        "dto.ReadPromptResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "createdUser": {
                    "$ref": "#/definitions/dto.CreatedUserResponse"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isPublic": {
                    "type": "boolean"
                },
                "llmName": {
                    "type": "string"
                },
                "parameters": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ParameterResponse"
                    }
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "dto.ReadPromptsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ReadPromptResponse"
                    }
                },
                "page": {
                    "$ref": "#/definitions/dto.BasePageResponse"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "version(1.0)",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "PromptSharing API",
	Description:      "PromptSharing API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
